language: node_js
node_js:
  - 12
env:
  - TRAVIS=true
services:
  - mongodb

# Don't do postgres
# before_script:
  # - psql -c 'create database entity_test;' -U postgres

# exclude work in progress
branches:
  except:
    - wip
